NaengPa/NaengPa-Frontend

- .gitignore
- src/common/axios.js
- src/pages/DetailPage/Detail.jsx
- src/pages/MainPage/ViewedRecipeImgList.jsx
- src/pages/SearchPage/Search.jsx
- src/pages/resultList.jsx
env파일에 숨기기, axios.js로 서버통신 옮기기작업 완료했습니다
> ✨ axios.js로 모든 통신 이관했고 그에따른 페이지별 코드수정좀 했습니다. 그리고 저희 서버주소 env파일에 숨기기

- src/common/doubleCheck.js
- src/common/kakaoLogin.js
- src/components/filter/filter.jsx
- src/components/filter/filterCategory.jsx
- src/components/filter/filterCategoryButton.jsx
- src/pages/LoginPage/login.jsx
- src/pages/SignIn/a.html
- src/pages/SignIn/signIn.jsx
- src/pages/resultList.jsx
- src/theme/theme.js
> ✨ 회원가입, 로그인페이지 로직완료 했습니다

- src/pages/resultList.jsx
- src/routes/protectedRoute.jsx
> filter test

- src/common/kakaoLogin.js
- src/components/filter/filter.jsx
- src/components/filter/filterCategoryButton.jsx
- src/pages/LoginPage/login.jsx
- src/pages/MyPage/MyPage.jsx
- src/pages/SignIn/a.html
- src/pages/resultList.jsx
> ✨ 로그인 기능 완성, 필터로직 거의완성

- src/Constant/constant.js
- src/components/filter/filter.jsx
- src/components/filter/filterCategoryButton.jsx
- src/pages/LoginPage/login.jsx
- src/pages/SearchPage/Search.jsx
- src/pages/resultList.jsx
- src/routes/protectedRoute.jsx
- src/routes/route.jsx
> 🐛 필터기능 버그수정

- src/pages/LoginPage/login.jsx
- src/pages/MyPage/MyPage.jsx
- src/routes/protectedRoute.jsx
- src/routes/route.jsx
로컬로그인 리프레시 토큰생겨서 로직 수정했고, 로그인되도 페이지 이동불가해결 + 로그인시 로딩창 생성
> ✨ 로컬로그인 로직수정, 로그인 로딩창 구현

- src/components/CommunityPage/CommunityArticle.jsx
> ✨  커뮤니티 카톡 공유 디폴트 이미지

- src/common/kakaoLogin.js
- src/components/frigeButton.jsx
- src/pages/LoginPage/login.jsx
- src/pages/MyFrigePage/MyFrige.jsx
- src/pages/resultList.jsx
결과페이지 로딩창 추가하고,냉장고페이지 스크롤바 없애기, 폰트굵기 통일했습니다.
> ✅ qa관련해서 수정했습니다

- src/assets/X_InActive.svg
- src/components/DetailPage/IngredientTagList.jsx
- src/components/MainPage/RecentlyViewedRecipe.jsx
- src/components/ShareModal/shareModal.jsx
- src/pages/FrigePage/Frige.jsx
- src/pages/LoginPage/findAndSignIn.jsx
- src/pages/MainPage/Main.jsx
- src/pages/MyFrigePage/MyFrige.jsx
- src/pages/MyPage/MyPage.jsx
- src/pages/SearchPage/Search.jsx
- src/pages/resultList.jsx
> 💄 qa부분 수정반영했습니다

- src/components/DetailPage/IngredientTagList.jsx
- src/components/MainLayout.jsx
- src/components/frigeButton.jsx
- src/pages/CommunityPage/Community.jsx
- src/pages/DetailPage/Detail.jsx
- src/pages/FrigePage/Frige.jsx
- src/pages/LoginPage/login.jsx
- src/pages/MyPage/MyPage.jsx
- src/pages/SearchPage/Search.jsx
- src/pages/SignIn/signIn.jsx
- src/pages/resultList.jsx
- src/routes/protectedRoute.jsx
detail페이지 항목로직 수정, 검색페이지 재료항목 빼는기능 추가, 서비스 모든 console제거, 결과페이지 height수정
> 🐛 버그수정, 콘솔삭제

- src/common/axios.js
- src/components/LoadingScreen.jsx
- src/components/ShareModal/linkShare.jsx
- src/components/ShareModal/shareModal.jsx
- src/components/filter/filter.jsx
- src/components/filter/filterCategoryButton.jsx
- src/components/navigation.jsx
- src/pages/CommunityPage/Community.jsx
- src/pages/SearchPage/Search.jsx
- src/routes/route.jsx
로딩창을 layout크기에 맞게 수정, 필터창 어색한 ui수정, 콘솔제거, 모바일클립보드 저장안되는버그 수정
> 🐛 ui수정, 모바일 클립보드 저장안되는거 해결

- src/assets/loading.svg
- src/pages/MyFrigePage/MyFrige.jsx
- src/pages/MyPage/MyPage.jsx
- src/pages/SearchPage/Search.jsx
마이페이지 로그아웃버튼 잘리는 ui수정, 검색페이지와 냉장고페이지에서 정보받아올때 로딩바 추가
> 💄 ui수정, 로딩인디케이터 추가

- src/pages/DetailPage/Detail.jsx
- src/pages/resultList.jsx
디테일페이지 로딩추가, resultlist페이지 안쓰는 state제거
> 💄 로딩추가, useState제거

- src/common/kakaoLogin.js
- src/pages/FrigePage/Frige.jsx
- src/pages/LoginPage/login.jsx
- src/pages/SearchPage/Search.jsx
- src/routes/page.js
콘솔 제거, 검색페이지 무한로딩버그 수정, 토큰저장관련 로직 수정
> 🐛 검색페이지 무한로딩, console

- public/index.html
> 📝 프로젝트 메인타이틀 수정

- public/index.html
- src/pages/LoginPage/Login.jsx
카카오 스크립트를 메인 헤드태그에서 불러오던걸 해당 페이지에서 불러와 웹 퍼포먼스 향상
> ⚡️ 카카오 스크립트수정, 퍼포먼스 향상

- src/pages/CommunityPage/Community.jsx
- src/pages/DetailPage/Detail.jsx
- src/pages/LoginPage/Login.jsx
kakao script를 사용 하는 모든페이지에서 불러오도록 코딩
> ⚡️ 퍼포먼스 관련 script수정

- package-lock.json
- package.json
- public/index.html
- src/index.js
- src/pages/MyFrigePage/MyFrige.jsx
- src/pages/ResultListPage/ResultList.jsx
- src/pages/SearchPage/Search.jsx
해당 값들에 캐시기능을 리액트쿼리로 구현했고, 기존 레거시들을 리액트 쿼리에 맞게 리팩토링
리액트 쿼리 라이브러리 추가
> ♻️ Search,Resultlist 리팩토링

- src/pages/LoginPage/Login.jsx
- src/pages/SearchPage/Search.jsx
리액트쿼리로 서버상태를 관리하면서 클라이언트 상태랑 결합된 부분을 수정하고 반영해서 버그를 잡았습니다.
> 🐛 검색시 시스템이 터지는 버그 수정

- src/pages/SearchPage/Search.jsx
react query로 리팩토링 하면서 버튼을 클릭해도 안 사라지는 버그를 수정
> 🐛 검색 container에서 버튼 클릭시 안사라지는 버그 수정

- src/pages/SearchPage/Search.jsx
해당 로직을 리코일에서 가져오던 값을 react-query로 서버상태의 값으로 화면을 구성하도록 수정
> 🐛 로그인됐어도 내 냉장고에서 골라보세요 활성화 안되는 bug수정
